name: VPS Infrastructure Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check VPS Resources
        run: |
          echo "===== VPS INFORMATION ====="
          echo "Hostname:"
          hostname

          echo
          echo "CPU:"
          nproc

          echo
          echo "RAM:"
          free -h

          echo
          echo "Disk:"
          df -h /

          echo
          echo "Ubuntu:"
          lsb_release -a

          echo
          echo "Public IP:"
          curl -4 https://api.ipify.org
          echo
          
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          tailscale version

      - name: Connect to Tailscale
        run: |
          sudo tailscale up --auth-key=${{ secrets.TS_AUTHKEY }}
          tailscale status
          tailscale ip -4
